### PR TITLE
BOM-1091

### PR DESCRIPTION
**Pull request by Ayub-Khan**
-Removed xblock.fragment support
-Removed runtime without id_generator support

### CODE REVIEW

**Comment by jmbowman** [comment]
DEPR-59 has been officially announced, we should be able to go ahead with the removal in mid-January.  I'll start creating tickets to fix other code we know about that still uses these.

**Comment by awais786** [comment]
@jmbowman can we merge this now ?

**Comment by ormsbee** [comment]
FYI @bradenmacdonald

**Comment by bradenmacdonald** [comment]
Cool, thanks for the heads up @ormsbee. Please just make sure that the corresponding updates to `openedx.core.djangoapps.xblock.runtime.runtime` and `.blockstore_runtime` are made at the same time as this is version bumped in edx-platform, and if possible please run the edx-platform+blockstore+runtime integration tests at the same time to make sure it works OK (they must still be run manually as they don't get run by Jenkins).

**Comment by ormsbee** [comment]
@awais786, @jmbowman: If we can hold off on this for another week or two, I'd really appreciate it. I need to fix how Blockstore XBlock runtime related tests get run in CI, which I can probably do in the next sprint.

**Comment by Ayub-Khan** [comment]
@ormsbee Any update regarding this.

**Comment by Ayub-Khan** [comment]
@ormsbee  @awais786 I will be closing this.

**Pull request closed without merging**
