### PR TITLE
Use svg coveralls badge

### PR DESCRIPTION
**Pull request by tusbar**
So it looks nicer next to the travis badge. :)

cc @sarina, @singingwolfboy

### CODE REVIEW

**Comment by sarina** [comment]
FYI you can get anyone to review these, doesn't have to be me! I can get to
these Monday if you can't find anyone else to review for you.

**Comment by tusbar** [comment]
@sarina alright.

I think I’m going to ask @talbs to review this one. :D
It’s very much design related.

**Comment by talbs** [comment]
Now this format change looks like "The Real Deal". Thx for the visual and image formatting clean up!

:+1:

**Comment by sarina** [comment]
:+1: Merge whenever!

**Pull request merged**
