### PR TITLE
Cache load_classes result

### PR DESCRIPTION
**Pull request by nasthagiri**
This adds an `openedx.yaml` file, as described by OEP-2:
http://open-edx-proposals.readthedocs.io/en/latest/oeps/oep-0002.html

The data in this file was transformed from the contents of
edx/repo-tools-data:repos.yaml

### CODE REVIEW

**Comment by cpennington** [comment]
@nasthagiri: Sorry, I wrote a piece of rogue automation that changed your PR title and message.

**Comment by feanil** [comment]
@nasthagiri @cpennington is this still relevant?

**Comment by cpennington** [comment]
Probably? I'm not sure how much of a perf win it is, but it can't hurt.

**Comment by feanil** [comment]
Looks like it's not trivially mergeable. Closing for now.

**Pull request closed without merging**
