### PR TITLE
Backup class cache in register_temp_plugin

### PR DESCRIPTION
**Pull request by cpennington**

### CODE REVIEW

**Comment by cpennington** [comment]
@nedbat @doctoryes: This is needed for https://github.com/edx/edx-platform/pull/7050

**Comment by nedbat** [comment]
One wonders why PLUGIN_CACHE is not a class attribute, but this fixes the test isolation. :+1:

**Comment by cpennington** [comment]
Because if it were, then we'd be back to the bad old days of having multiple caches depending on which of `XModule`, `XBlock`, or `XModuleDescriptor` you happened to try and load the plugins through.

**Comment by doctoryes** [comment]
:+1:

**Comment by nedbat** [comment]
We could make it Plugin.global_cache, and access it that way, not as cls.global_cache.

**Comment by cpennington** [comment]
Yeah, I guess that's true. Better, though?

**Comment by nedbat** [comment]
You already have my :+1: :)

**Pull request merged**
