### PR TITLE
mattdrayer/increment-release-version: Bump to 0.4.7

### PR DESCRIPTION
**Pull request by mattdrayer**
@doctoryes, FYI

### CODE REVIEW

**Comment by doctoryes** [comment]
Just curious: Why did you skip `0.4.6`?

**Comment by mattdrayer** [comment]
I accidentally made the 0.4.6 release tag ahead of updating the setup.py, so it points to the commit hash just before.  Figured it was easiest to skip ahead to 0.4.7 and once this merges I will create another tag.

**Comment by doctoryes** [comment]
:+1:

**Comment by mattdrayer** [comment]
Nice, thanks!  Merging now

**Pull request merged**
