### PR TITLE
[MCKIN-7023] Make XBlock services available to template render context

### PR DESCRIPTION
**Pull request by pomegranited**
Adds `i18n` support for XBlock Django templates passing all the XBlock's loaded services into the template render `context`.  This change also allows other services to be used during template rendering.

**JIRA tickets**: [MCKIN-7023](https://edx-wiki.atlassian.net/browse/MCKIN-7023), [OSPR-2279](https://openedx.atlassian.net/browse/OSPR-2279)

**Discussions**: [WL-230](https://openedx.atlassian.net/browse/WL-230), [YONK-879](https://openedx.atlassian.net/browse/YONK-879?focusedCommentId=307771&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-307771)

**Dependencies**:

No dependencies, but this change is related to https://github.com/edx/xblock-utils/pull/48

**Screenshots**: See https://github.com/edx-solutions/xblock-drag-and-drop-v2/pull/154 for before and after screenshots using dummy translations.

**Sandbox URL**:  sandbox is being provisioned.

* LMS: https://pr17670.sandbox.opencraft.hosting/
* Studio: https://studio-pr17670.sandbox.opencraft.hosting/

**Merge deadline**: None

**Testing instructions**:

See https://github.com/edx-solutions/xblock-drag-and-drop-v2/pull/154 for test instructions.

**Reviewers**
- [ ] @mtyaka 
- [ ] edX reviewer[s] TBD

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @pomegranited! I've created [OSPR-2287](https://openedx.atlassian.net/browse/OSPR-2287) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/XBlock/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by nedbat** [comment]
@edx/platform-team Not an OSPR, but you might have opinions...

**Comment by bradenmacdonald** [comment]
@pomegranited An alternative would be to change the signature of `render_django_template(self, template_path, context=None)` to `render_django_template(self, template_path, context=None, i18n_service=None)`, and then have each XBlock pass in that service explicitly, right? I think that many (most?) XBlocks currently don't use their XBlock `context` parameter as the basis of the template context, so most XBlocks already need to be changed anyways. 

We could also move [XBlockWithTranslationServiceMixin](https://github.com/open-craft/problem-builder/blob/de8f2dfa4d87fde922c7190c7f30f4b7585e66a2/problem_builder/mixins.py#L33) to xblock-utils and put some helper code in there.

**Comment by pomegranited** [comment]
@bradenmacdonald Sure, we could have each XBlock pass in the `i18n` service explicitly into the context, but every XBlock would need to use the same key on the context to ensure that the [templatetag in `xblock-utils`|https://github.com/edx/xblock-utils/pull/48/files#diff-e9896972393a0c47da57c397faa051d2R29] can find it, and that feels brittle.

**Comment by bradenmacdonald** [comment]
@pomegranited That's why I meant to pass it as a fourth parameter to `render_django_template` and have *that* shared code set the "internal" context variable. So it would be part of the parameter API of `render_django_template` which shouldn't be too brittle.

I'm not saying that's a better approach overall, but wanted to lay out another option in case people don't like this approach.

**Comment by pomegranited** [comment]
@bradenmacdonald  Ah ok, I understand now!  Will see what edX say.

**Comment by edx-webhook** [comment]
Although this pull request is already closed, I've created [OSPR-5486](https://openedx.atlassian.net/browse/OSPR-5486) so that we can track it in Jira.

There is nothing you have to do. No action is needed from your side.  Thanks.

**Pull request closed without merging**
