### PR TITLE
Revert "String field return empty string for None"

### PR DESCRIPTION
**Pull request by Shrhawk**
[PLAT-736](https://openedx.atlassian.net/browse/PLAT-736)

Reverted the related pr [#8889](https://github.com/edx/edx-platform/pull/8889) on edx -platform produce issue [TNL-3031](https://openedx.atlassian.net/browse/TNL-3031).

### CODE REVIEW

**Comment by Shrhawk** [comment]
@adampalay @waheedahmed this will revert https://github.com/edx/XBlock/pull/305

**Comment by adampalay** [comment]
@cpennington 

:+1:

**Comment by cpennington** [comment]
:+1:

**Comment by cpennington** [comment]
It would be nice to move this fix to `to_string` and `from_string` to fix the original issue with XML import/export.

**Pull request merged**
