### PR TITLE
remove unicode literals

### PR DESCRIPTION
**Pull request by efischer19**
Attempting to resolve failure seen here, under a python 2.7 environment: https://travis-ci.org/edx/edx-ora2/jobs/255407697

### CODE REVIEW

**Comment by efischer19** [comment]
Fix made after finding https://github.com/arvindch/pockyt/issues/9 via googling.

@nedbat, you're the best python references I know of, does this change seem reasonable to you? It solved the test failures I was seeing after upgrading ora to the latest version of this code, example run at https://travis-ci.org/edx/edx-ora2/jobs/255407697

**Comment by efischer19** [comment]
@jmbowman, it looks like you've been involved in the python3 OEP work - is there a doc page where I can record this* as a potential gotcha when migrating a repo?

* - this = "don't use unicode for metadata fields in `setup.py`"

**Comment by jmbowman** [comment]
Maybe just create a PR to add that note to the OEP under http://open-edx-proposals.readthedocs.io/en/latest/oep-0007.html#handling-literals-option-1-python-3-style ?  I'm also making a note to create some kind of linting rule for this.

**Comment by nedbat** [comment]
Sorry I was out for this.  I had not heard of this limitation before!

**Pull request merged**
