### PR TITLE
Switch to the new travis infrastructure

### PR DESCRIPTION
**Pull request by tusbar**
cc @sarina

### CODE REVIEW

**Comment by sarina** [comment]
This is probably better for DB to look at.

**Comment by tusbar** [comment]
Hello @singingwolfboy :)

**Comment by singingwolfboy** [comment]
Looks good to me! :+1: 

If you want to go the extra mile, you might want to also [turn on dependency caching](http://docs.travis-ci.com/user/caching/#pip-cache). Adding `cache: pip` to the file should do it.

**Comment by tusbar** [comment]
@singingwolfboy good idea, done.

**Comment by tusbar** [comment]
@singingwolfboy good for merging? :+1:

**Comment by singingwolfboy** [comment]
@tusbar :+1: :shipit:

**Pull request merged**
