### PR TITLE
[BD-18] remove nose footprints from the project

### PR DESCRIPTION
**Pull request by emzubair**
## remove nose footprints from the project

**Packages Removed**

- nose

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @emzubair! I've created [BLENDED-405](https://openedx.atlassian.net/browse/BLENDED-405) to keep track of it in Jira.

When this pull request is ready, tag your edX technical lead.

**Comment by edx-webhook** [comment]
Hello @emzubair: We are unable to continue with review of your submission at this time. Please see the associated JIRA ticket for more explanation.

**Comment by awais786** [comment]
> Looks good to me, is there a reason it's a draft PR?

@feanil CI status is not coming and merge button is disabled. 
https://travis-ci.community/t/travis-ci-branch-expected-waiting-for-status-to-be-reported/829

**Comment by feanil** [comment]
It was an issue with us requiring branch tests but they don't get run on forks, I fixed it so it should not be an issue again on this repo.

**Pull request merged**
