### PR TITLE
Fix a few typos

### PR DESCRIPTION
**Pull request by nikolas**
Found with codespell

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @nikolas! I've created [OSPR-2571](https://openedx.atlassian.net/browse/OSPR-2571) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by mduboseedx** [comment]
jenkins ok to test

**Comment by mduboseedx** [comment]
@nikolas Thanks for the fixes! I'll merge the changes.

**Comment by edx-webhook** [comment]
@nikolas 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/XBlock&entry.867055334=https://github.com/edx/XBlock/pull/384&entry.1484655318=https://github.com/nikolas&entry.752974735=2018-08-28+01:53&entry.1917517419=2018-09-05+14:06&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
