### PR TITLE
Have to install all the packages

### PR DESCRIPTION
**Pull request by nedbat**

### CODE REVIEW

**Comment by nedbat** [comment]
@cpennington the setup.py was a little wrong. This commit works well in edx-platform.

**Comment by nedbat** [comment]
@doctoryes @macdiesel ??

**Comment by cpennington** [comment]
:+1:

**Comment by doctoryes** [comment]
:+1:  Will you be bumping the edx-platform version number next?

**Comment by macdiesel** [comment]
:+1:

**Pull request merged**
