### PR TITLE
Documentation updates

### PR DESCRIPTION
**Pull request by dhruvbaldawa**
I have just tweaked some sphinx-build arguments so that Sphinx builds the documentation when the source files are also changed.

Changed XBlock documentation to also show the inherited members and added few clarifications to the handlers' documentation.

### CODE REVIEW

**Comment by sarina** [comment]
Hi @dhruvbaldawa - we need you to follow the bot's instructions about the contributor agreement and adding yourself to AUTHORS before we can continue with your PR. Please ping me if you have any questions or need any help!

**Comment by sarina** [comment]
@dhruvbaldawa otherwise this PR looks reasonable! Once your contributor's agreement is in, I'll have a member of our doc team take a check on the Sphinx stuff and we should be able to get this quickly merged.

**Comment by dhruvbaldawa** [comment]
Thanks @sarina, I have sent the agreement and updated the AUTHORS file

**Comment by sarina** [comment]
@dhruvbaldawa received your agreement, thanks! Am going to ask someone on the Doc team to take a look at your Sphinx syntax.

**Comment by mhoeber** [comment]
:+1:   thanks

**Comment by sarina** [comment]
@dhruvbaldawa thanks so much for this contribution to the platform! Hope to see you in here again :)

**Pull request merged**
