### PR TITLE
Add pypi version badge

### PR DESCRIPTION
**Pull request by tusbar**
Just because it’s cool.

cc @sarina, @singingwolfboy

### CODE REVIEW

**Comment by singingwolfboy** [comment]
Sounds good to me. :+1:

**Comment by sarina** [comment]
What do we have on PyPi? @singingwolfboy do you know who is responsible for pushing pypi versions of this repo? AFAIK we're not incorporating pypi into our dev cycles (we _should_ but so far we havne't)

**Comment by tusbar** [comment]
The issue with this is that the badges won’t all stay on the same line. :(

**Comment by singingwolfboy** [comment]
@sarina I don't think anyone at edX is responsible for pushing PyPI versions of the repo right now. This seems like something that would fall to the platform team.

**Comment by sarina** [comment]
@tusbar I'm not sure we want to advertise this badge until we're actively using pypi to distribute the package.

**Comment by tusbar** [comment]
@sarina alright! I thought it was up to date!

**Comment by sarina** [comment]
It's last updated November 2014. https://pypi.python.org/pypi/XBlock/0.4

**Comment by tusbar** [comment]
Yes indeed. It would be nice to have dependencies like XBlock on pypi. So `pip install` would not spend so much unnecessary time resolving github refs.

**Comment by sarina** [comment]
I agree! I'll put a ticket to start doing this for xblock.

**Pull request closed without merging**
